/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.flipperplz.bisutils

import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        //TODO("Write unit tests")
    }
}
